### ISSUE TITLE
Chestswap

### ISSUE THREAD

**Issue by NotJohnmcswag** [DarkiBoi/konas-issues#10]
Add a module that lets you automatically swap between elytra and chestplate

**Comment by DarkiBoi** [comment]
elytraprio on autoarmor ;(

**Comment by NotJohnmcswag** [comment]
yeah but chestswap would be better ;(

**Comment by zyktex** [comment]
Yeah just took a look at autoarmor, there's already a mode for that. Adding a seperate module would be bloat
