### ISSUE TITLE
Watermark & Nametags

### ISSUE THREAD

**Issue by Bignamer-zPrestige** [DarkiBoi/konas-issues#116]
Dear konas Devs,

Watermark:

Add modes: Text - Image - Both

New Mode: Both -> This makes it so instead of just the watermark or the text, it displays both of those. 

Nametags:

NO LAG MY FPS GO POOPOO AND I HAVE TO USE CREEPY SAL >:(

ReverseStep:

Glitches when you are going down 3 or more blocks, my pyro one works fine but idk

**Comment by zyktex** [comment]
ReverseStep is fastfall. Use the "Reverse" mode in step instead. Nametags performance has been increaced in 0.7
