### ISSUE TITLE
Rubber Fill

### ISSUE THREAD

**Issue by KoolKillm8** [DarkiBoi/konas-issues#124]
Make an autodisable for rubberfill since if they get in your hole it turns into auto jump/suicide since your opponent can place crystals at your feet when you jump.

**Comment by DachaBager** [comment]
Ur a retard for using burrow anyways, i say remove it from client

**Comment by rexvonzombie** [comment]
> Ur a retard for using burrow anyways, i say remove it from client

No, pyro and xulu exist

**Comment by Boerenkool** [comment]
I'd like to see that too
