### ISSUE TITLE
Stop PacketFly's AntiKick from descending while phasing

### ISSUE THREAD

**Issue by rexvonzombie** [DarkiBoi/konas-issues#126]
While your feet are inside a block you won't get kicked for fly, so there's really no need for AntiKick to keep descending. Maybe make this an optional setting for people who don't mind descending while in a block.

**Comment by zyktex** [comment]
Make sure you're using Phase NCP

**Comment by rexvonzombie** [comment]
> Make sure you're using Phase NCP

Even on phase NCP, the antikick will descend while phasing in blocks
