### ISSUE TITLE
Hud Editor

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#129]
-Make hud look like in phobos and future
-Add ping and other cool shit
-Make it look like this as deafult ( but make it so you can edit it aswell )
![image](https://user-images.githubusercontent.com/72751613/102021427-08f03400-3d80-11eb-849a-331550d5d04d.png)

**Comment by zyktex** [comment]
We already have hudeditor with ping, etc. Making a default arrangements would be impossible due to different screen sizes (unless we directly scaled hud with screen size)
