### ISSUE TITLE
Add DisableOnStep to Surround

### ISSUE THREAD

**Issue by rexvonzombie** [DarkiBoi/konas-issues#133]
If surround is on and you go up a block using step, create a setting to autodisable surround, since this is almost the equivalent to jumping.

**The current DisableOnJump setting does NOT disable when using step. This is NOT already implemented in b0.6.2**

**Comment by very-cashmoney** [comment]
LOL NO JUST DISABLE IT NOOB XD

**Comment by zyktex** [comment]
I just tested it and it works fine, stop spamming issues
