### ISSUE TITLE
Stop PacketFly's AntiKick from descending while phasing

### ISSUE THREAD

**Issue by rexvonzombie** [DarkiBoi/konas-issues#134]
While your feet are inside a block you won't get kicked for fly, so there's really no need for AntiKick to keep descending. Maybe make this an optional setting for people who don't mind descending while in a block.

**The Phase NCP does NOT stop antikick from descending while in blocks. This is an antikick suggestion, not a phase mode suggestion**

**Comment by very-cashmoney** [comment]
cope

**Comment by zyktex** [comment]
Added in 0.7.2
