### ISSUE TITLE
compatibility with phobos 

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#138]
yes plese copmatibility with phobos 1.5.4

**Comment by rexvonzombie** [comment]
would be nice

**Comment by XZRC** [comment]
why the fuck would you use phobos?

**Comment by DachaBager** [comment]
> why the fuck would you use phobos?

because its probbably best client for pvp 🤡

**Comment by very-cashmoney** [comment]
sure thing! ill tell the devs and they will start working on it brother

**Comment by zyktex** [comment]
Compatibility issues are their fault
