### ISSUE TITLE
Friends and fps drops issue

### ISSUE THREAD

**Issue by ElMantoMc** [DarkiBoi/konas-issues#147]
Idk why maybe a bug when adding and deleting friends it happends that your konasconfig gets filled with the same ppl friendend multiple times that makes your client drop a lot of fps when turning on crystal aura when there is more than 1 ppl in your render distance, i had to delete my konas config to be able to pvp again, thx for konas and merry xmas

**Comment by very-cashmoney** [comment]
seems like cope

**Comment by DarkiBoi** [comment]
ill look into this

**Comment by DarkiBoi** [comment]
fixed
