### ISSUE TITLE
[Suggestion] offhand cycle mode

### ISSUE THREAD

**Issue by system69-e** [DarkiBoi/konas-issues#148]
so basically a mode on offhand that lets you switch between gaps, crystals, and totems using a hotkey instead of being "automatic" , while having the option to fall back to autototem when you are under a given health. 

the option to automatically switch to gap or totem when holding the sword instead of forcing totem will also be great but it is not necessary however would be a nice-to-have.

**Comment by zyktex** [comment]
You can already do this with macros
