### ISSUE TITLE
[suggestion] offhand cycle mode

### ISSUE THREAD

**Issue by system69-e** [DarkiBoi/konas-issues#149]
so basically a mode on offhand that lets you switch between gaps, crystals, and totems using a hotkey instead of being "automatic" , while having the option to fall back to autototem when you are under a given health.

the option to automatically switch to gap or totem when holding the sword instead of forcing totem will also be great but it is not necessary however would be a nice-to-have.

p.s: ik its possible with macros, there is a reason I am resubmitting this, macros are not reliable as people want this in the client itself, not some retarded ass macro.

**Comment by zyktex** [comment]
Macros are entirely reliable. Having a bind option would not have any advantages. If you are unable to create a macro place ask support
