### ISSUE TITLE
Surround with antighost block feature

### ISSUE THREAD

**Issue by Toshimichi0915** [DarkiBoi/konas-issues#179]
Now surround module sometimes create ghost blocks, which is critical during Crystal PvP.
My idea is to interact with obsidian placed by surround module.
In that way, the server will send block update(air) to the client if the obsidian was not correctly placed, which will prevent critical issue with ghost blocks

**Comment by Toshimichi0915** [comment]
it will also be amazing if the module spams blockplace packet even after the block was placed, to prevent ghost blocks and chain pop

**Comment by blgbrain** [comment]
if you turn your blocks per tick down it should fix it same with tick speed.

**Comment by zyktex** [comment]
Use NoDesync Position. This won't place blocks client side
