### ISSUE TITLE
Trajectories are ugly. Maybe make them like xulu or phobos?

### ISSUE THREAD

**Issue by Lempity** [DarkiBoi/konas-issues#189]
Trajectories are ugly. Maybe make them like xulu or phobos?

**Comment by blgbrain** [comment]
phobos has a white one so go into the tragectories settings change the color to white, turn off rainbow, and turn the width down. bascially the same

**Comment by zyktex** [comment]
Yes, colors are completely customisable. Right click on the module in ClickGUI to customise the colors and line width
