### ISSUE TITLE
BUG: AutoCrystal being a retard

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#190]
https://streamable.com/eat0vk
![image](https://user-images.githubusercontent.com/72751613/105873855-36c1cd00-5ffc-11eb-9f52-3cad8c076b45.png)
![image](https://user-images.githubusercontent.com/72751613/105873904-42ad8f00-5ffc-11eb-8b7f-ebfb71079145.png)
![image](https://user-images.githubusercontent.com/72751613/105873940-4e995100-5ffc-11eb-8bda-fefdd16f7a6a.png)

Mods used: Phobos 1.7.2
                   Baritone
                   Optifine
                   Konas

**Comment by blgbrain** [comment]
if you're talking about it stopping its doing that to stop you from popping yourself
you have anti suicide on

**Comment by DachaBager** [comment]
> if you're talking about it stopping its doing that to stop you from popping yourself
> you have anti suicide on

im talking about ca working even tho it cant do any damage because fakeplayer is in sorround

**Comment by DachaBager** [comment]
> if you're talking about it stopping its doing that to stop you from popping yourself
> you have anti suicide on

i posted a video if you didnt notice https://streamable.com/eat0vk

**Comment by blgbrain** [comment]
ah its your armour depletion
turn that to 0.8
right now its set you where it will waste crystals to completely break opponents armour

**Comment by blgbrain** [comment]
what that'll do is start faceplacing low dmg crystals when their armour is at 20% durability

**Comment by 2147483647ms** [comment]
config error

**Comment by zyktex** [comment]
Turn up compromise. That is the issue. Next time, please ask in support.
