### ISSUE TITLE
SUGGESTION: Holefill predict mode

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#193]
mode in holefill which predicts in which hole the enemy will go and autoholefills it without user having to do anything, if done right would be op

**Comment by blgbrain** [comment]
dude this is like coding a human. its very difficult to predict human decisions using ai. possible but unlikely

**Comment by DachaBager** [comment]
> dude this is like coding a human. its very difficult to predict human decisions using ai. possible but unlikely

It already exsists in some clients and konas ca has it

**Comment by twentyfived2** [comment]
Konas CA doesn't predict enemy movement as far as I'm aware of. No CA does for that matter
