### ISSUE TITLE
Block hit push animation yes i know 1.12.2 does not have block hit it just looks really good

### ISSUE THREAD

**Issue by 2147483647ms** [DarkiBoi/konas-issues#194]
Alot a 1.8/1.7 clients have this usually its in the "killaura" module or a module called "animations".

all this module would do is a add a customizable animation to hitting if you watch 1.8 hacking videos you should be able to look at the sword and see what these animations look like as it is very hard to explain what they look like.

**Comment by zyktex** [comment]
OldAnimations is already a module
