### ISSUE TITLE
SUGGESTION: make a separate module called crystaleditor or smth

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#196]
make a module with which you can combine and use chams and wireframe crystal mode so it looks sexy like this
![image](https://user-images.githubusercontent.com/72751613/106046955-3f410300-60e3-11eb-9d5e-fc338e70bb5e.png)
![image](https://user-images.githubusercontent.com/72751613/106047271-ae1e5c00-60e3-11eb-8ca3-a3ff92f92afe.png)
![image](https://user-images.githubusercontent.com/72751613/106047352-cbebc100-60e3-11eb-8f83-df89a9bdc10c.png)

**Comment by TransRights** [comment]
Added in 0.8
