### ISSUE TITLE
SUGGESTION: make a sexier holeesp

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#197]
![image](https://user-images.githubusercontent.com/72751613/106047570-0fdec600-60e4-11eb-9a08-fe47ba73a84d.png)
![image](https://user-images.githubusercontent.com/72751613/106047602-179e6a80-60e4-11eb-836c-ad00980972ce.png)
![image](https://user-images.githubusercontent.com/72751613/106047646-25ec8680-60e4-11eb-9e32-3e50c3513f5f.png)

**Comment by blgbrain** [comment]
just use pyro if you have it. if not you can use crystalinqq's crack. so far to our knowledge it safe

**Comment by DachaBager** [comment]
> just use pyro if you have it. if not you can use crystalinqq's crack. so far to our knowledge it safe

Yes i have pyro and its ugly as fuck, bad client, and a skid. And it doesnt have this type of holeesp

**Comment by blgbrain** [comment]
thats pyro holeesp im pretty sure

**Comment by 2147483647ms** [comment]
> thats pyro holeesp im pretty sure

thats phobos

**Comment by blgbrain** [comment]
> > thats pyro holeesp im pretty sure
> 
> thats phobos

is it i didnt know

**Comment by blgbrain** [comment]
also pretty sure its coming in 0.8

**Comment by zyktex** [comment]
> also pretty sure its coming in 0.8

yes
