### ISSUE TITLE
Pistonaura "specialPlace" mode

### ISSUE THREAD

**Issue by Tux8068** [DarkiBoi/konas-issues#207]
this mode places pistons in a different way, look at the attached imgur links for a visual explenation. (this bypasses AntiPA btw)
https://imgur.com/a/OpMT4o9
https://imgur.com/a/LbR1yf7

**Comment by blgbrain** [comment]
gamesense has it use that

**Comment by zyktex** [comment]
Placement algorithm has already been rewritten for 0.8
