### ISSUE TITLE
OldAnimations bug

### ISSUE THREAD

**Issue by Tux8068** [DarkiBoi/konas-issues#210]
while using viewmodel and OldAnimations, viewmodel is reset on your offhand
to replicate:
use viewmodel and change your offhand to anything, then  turn OldAnimations on

**Comment by zyktex** [comment]
Are you using Konas's viewmodel and OldAnimations?

**Comment by Tux8068** [comment]
yes

**Comment by TransRights** [comment]
Unable to reproduce
