### ISSUE TITLE
Crash with diferent clients

### ISSUE THREAD

**Issue by Alphazs** [DarkiBoi/konas-issues#214]
When i first loaded konas i loaded with phobos rhack and future cuz why not, i ran it and it was running ok and perfect, then i took out rhack out of my mods folder and then it started crashing with or without it, i have compatibility fix so i dont need to worry about that, dm me on discord if u want any other info ALPHA#1337

**Comment by zyktex** [comment]
Phobos is not compatible with Konas nor most other clients. This is not an issue on our side
