### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Alphazs** [DarkiBoi/konas-issues#215]
i play 2b alot and borrow is kinda usefull sometimes and theres a glitch were sometimes just pushes u outside the block or teleport u like upwards, i got the configs and dis is a /
suggestion/bug, and it was to made so whne u borrow outside the block it stays in the block without pushing u and doesent move u at all, on 2b would be rly usefull and i can test it if u guys want to im up to it

**Comment by DarkiBoi** [comment]
Closed because duplicate of #216
