### ISSUE TITLE
Add Client Side Mute

### ISSUE THREAD

**Issue by Alphazs** [DarkiBoi/konas-issues#218]
its simple, adding client side mute so with a command in game u can mute people without they noticing

**Comment by DarkiBoi** [comment]
Should the mutes be saved to config or would that be confusing

**Comment by Alphazs** [comment]
> Should the mutes be saved to config or would that be confusing

no, it would be confusing so just keep it the same way in diferent configs cuz if u mute someone u dont want to mute him 5 times on diferent configs u know?, so like mute him permanently

**Comment by Alphazs** [comment]
> Should the mutes be saved to config or would that be confusing

so it makes a save on konas.config or smth idk
