### ISSUE TITLE
[BUG] Player Module in InvGUI rendering incorrectly.

### ISSUE THREAD

**Issue by arlomcwalter** [DarkiBoi/konas-issues#222]
### Player Module in InvGUI rendering incorrectly.

**Description**  
When using konas, sometimes the playermodel in the players inventory GUI is rendered weirdly. Can't seem to pin down what is causing it so i assume it is some incorrect GL statement.

**Steps to reproduce:**  
1. Open the Inventory
2. View bug¿?

**Screenshots:**  
Expected:
![image](https://user-images.githubusercontent.com/17166139/106545532-71969a00-6501-11eb-87c7-d2201162c0f4.png)
Issue:
![image](https://user-images.githubusercontent.com/17166139/106545501-65124180-6501-11eb-811d-cded67969f89.png)

**Additional info**  
OS: Mac OS Big Sur
Java Version: JDK 8 v281

**Comment by DarkiBoi** [comment]
Can easily be fixed, will add in next update

**Comment by gigglingbed** [comment]
> Can easily be fixed, will add in next update

Sounds great, are you happy for me to close the issue?

**Comment by DarkiBoi** [comment]
I'll close it myself once I've fixed it

**Comment by Walaryne** [comment]
Can confirm also happening to me on Manjaro Linux.

**Comment by Walaryne** [comment]
The cause of the issue is when the Inventory overlay is enabled in Containers. I spent some time to narrow it down.
If you disable it, the issue goes away completely. (Could be related to the clear/backgroundless setting, as I have that enabled too).
Hope it helps Darki.

**Comment by gigglingbed** [comment]
:trollface:
