### ISSUE TITLE
[FEATURE] Auto-saving configs.

### ISSUE THREAD

**Issue by gigglingbed** [DarkiBoi/konas-issues#226]
### Auto-saving configs.

It would be great to implement automatically saving configs, i know that in beta they save on shutdown but it can be useful and inexpensive to save in other places such as the pause menu because, considering writing to a lot of files **could** cause a short lag on some machines, it wouldn't really be noticeable. This would mean that configs dont get lost as much.

I haven't really looked into it and i'm not sure how your auto save hooks work but if it isn't, you could try to implement saving before crashing. 

Also some Mixin to the crash report stacktrace to give the log more information about the client. [Here](https://github.com/MeteorDevelopment/meteor-client/blob/master/src/main/java/minegame159/meteorclient/mixin/CrashReportMixin.java) is an example of how that could be implemented.

**Comment by TransRights** [comment]
AutoSaving on pause has been added in 0.9.1 CrashReportMixin will be added soon
