### ISSUE TITLE
[FEATURE] Preset Configs for Diferent servers

### ISSUE THREAD

**Issue by Alphazs** [DarkiBoi/konas-issues#229]
### Title : Preset configs
make preset configs for some servers so it can me simple

when u open a movement/combat module add pre set configs so instead of having a bunch of diferent configs have pre set ones for the main servers like 2b, alot of client have it but just in 1 module so it will make module configging easier and simple when playing diferent servers, when i say preset configs for diferent servers it can me a mode that works fine on the server so it will explain that

**Additional info**  
It could be added mostly in movement and misc modules like holefill, noslow, elytraflight, borrow etc

**Comment by DarkiBoi** [comment]
I would like to add configs that get loaded when you join a certain server

**Comment by Alphazs** [comment]
> I would like to add configs that get loaded when you join a certain server

it would be super cool and usefull, idk its a good idea that i havent seen in a client idk if its easy to do

**Comment by TransRights** [comment]
This was added in 0.8
