### ISSUE TITLE
[FEATURE] make so you can bind stuff on mouse4 and mouse5

### ISSUE THREAD

**Issue by dizzyf** [DarkiBoi/konas-issues#236]
tittle

**Comment by 2147483647ms** [comment]
in your mouses software bind m4 or m5 to any key then bind the module to that key

**Comment by dizzyf** [comment]
> 
> 
> in your mouses software bind m4 or m5 to any key then bind the module to that key

cba, every other client/cheat has it

**Comment by DarkiBoi** [comment]
> > in your mouses software bind m4 or m5 to any key then bind the module to that key
> 
> cba, every other client/cheat has it

examples of what clients have it? never seen it in an anarchy client tbh

**Comment by dizzyf** [comment]
> > > in your mouses software bind m4 or m5 to any key then bind the module to that key
> > 
> > 
> > cba, every other client/cheat has it
> 
> examples of what clients have it? never seen it in an anarchy client tbh

rusherhack i'm pretty sure. i'm a csgo hvher so im used to binding stuff to my mouse

**Comment by TransRights** [comment]
This will be in 0.8
