### ISSUE TITLE
[BUG]Anchor rubberband when entering a hole

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#239]
### Title  
A short summary of the bug (no more than 10 words).

**Description**  
A clear description the bug.

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
If applicable, add screenshots to show the issue.

**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by Toshimichi0915** [comment]
```java
    fun centerPlayer(tp: Boolean): Boolean {
        val centerDiff = getCenterDiff()
        val centered = isCentered()
        if (!centered) {
            if (tp) {
                val posX = mc.player.posX + (centerDiff.x).coerceIn(-0.2, 0.2)
                val posZ = mc.player.posZ + (centerDiff.z).coerceIn(-0.2, 0.2)
                mc.player.setPosition(posX, mc.player.posY, posZ)
            } else {
                mc.player.motionX = (centerDiff.x / 2.0).coerceIn(-0.2, 0.2)
                mc.player.motionZ = (centerDiff.z / 2.0).coerceIn(-0.2, 0.2)
            }
        }
        return centered
    }

    private fun isCentered(): Boolean {
        return getCenterDiff().length() < 0.2
    }

    private fun getCenterDiff(): Vec3d {
        return Vec3d(roundToCenter(mc.player.posX), mc.player.posY, roundToCenter(mc.player.posZ)).subtract(mc.player.positionVector)
    }
```
copy and paste this code (from Kami Blue) and easy fix
https://github.com/kami-blue/client/pull/2087
Plz refer to my PR in Kami Blue Project
