### ISSUE TITLE
Make Nametags better

### ISSUE THREAD

**Issue by NotJohnmcswag** [DarkiBoi/konas-issues#24]
Add an outline to them and make absorption health green instead of brown, add a pop counter to it, make the item enchant text bigger and make it so it doesnt get bigger when you get closer to the person.

**Comment by DarkiBoi** [comment]
first of all absorption health is golden, because the absorption hearts in your healthbar are also golden

**Comment by NotJohnmcswag** [comment]
thats dumb, at least make an option for it

**Comment by DarkiBoi** [comment]
Alright, and also the nametag doesnt get bigger when you get closer to the person, its the other way around
