### ISSUE TITLE
[BUG] PistonAura doesnt find Pistons with Russian Localization

### ISSUE THREAD

**Issue by jj-inc** [DarkiBoi/konas-issues#240]
### Title  
Piston aura

**Description**  
When I used Russian language (in minecraft)  pistonaura has issue. 
![20210209_202819](https://user-images.githubusercontent.com/78823766/107426127-e33d9c00-6b30-11eb-971d-15ad01dbdef3.jpg)
Fix pls :>

**Comment by DarkiBoi** [comment]
Fix will be coming in next update
