### ISSUE TITLE
[BUG] Hole filler bug

### ISSUE THREAD

**Issue by HelpMopDog** [DarkiBoi/konas-issues#242]
### Title  
A short summary of the bug (no more than 10 words).
Hole filler wont re fill prev hole filled holes
**Description**  
A clear description the bug.
So basically this may be a 2b specific bug but still important. So basically you hole fill a hole but then if said block/web/anything that was placed inside is removed from the hole it will cause the hole filler to bug out and try and replace it alot and cause alot of weird rotating.
**Steps to reproduce:**  
1. create hole 
2. open gui
3. toggle hole fill
4. fill hole
5. break block in hole
6. Re toggle holefill
7. watch it bug out
Also this is a pretty detrimental bug cause if im web filling someone and i try and re fill it so they cant jump out it just wont work
**Screenshots:**  
If applicable, add screenshots to show the issue.
https://streamable.com/wat8b1
**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 https://streamable.com/wat8b1 pyro future and konas and my settings https://cdn.discordapp.com/attachments/804560147712180284/808963521983283210/2021-02-09_23.31.59.png btw changing the settings doesnt fix it tho also my discord is Helpmop#9999
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by TransRights** [comment]
This was fixed in 0.9
