### ISSUE TITLE
[FEATURE] Holetp

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#246]
### Title  
Being able to teleport to a hole within 1 block radius on X, Y and Z coordinates.

**Description**  
I know there's ReverseStep. But I saw this feature on one guy's stream. He was able to teleport into a hole (I think on specific server. It either was cpvp or 2bpvp, I think it was cpvp.. Not sure now). Idk how he did it, but it's pretty much like a blink (I guess), but it find hole for you.

**Comment by TransRights** [comment]
Anchor and reversestep (fastfall) already does this.
