### ISSUE TITLE
[FEATURE] Toggle Packetmine

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#247]
### Title  
You hold LMB - normal mine, press once - packetmine

**Description**  
Title explains everything. But basically if you hold left mouse button, you get a normal mine (maybe speedmine), and if you press it once, it will trigger packetmine. Should be a really good addition. (make it addition to packetmine. So ppl can choose which one they want to use. Either just packetmine or the one I explained, so it's not forced)

**Comment by TransRights** [comment]
Added in 0.9.2
