### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CallMeDad420** [DarkiBoi/konas-issues#248]
### Installer
cant log in on the installer

**Description**  
i can open the installer but when i try and log in and press the button its does nothing, good or wrong passwords there is no difference. ps: its doesnt crash or freeze for me i can spam the log in button 144 fps no problem

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
If applicable, add screenshots to show the issue.

**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by DarkiBoi** [comment]
Known issue that's already bein investigated. These issues are only related to the client tho, which is why I'm going to close this ticket
