### ISSUE TITLE
[FEATURE] Rotate on packetmine

### ISSUE THREAD

**Issue by Alphazs** [DarkiBoi/konas-issues#249]
### Title  
Ritate on packet mine so u can packet mine on rotate servers
**Description**  
When packet mine is used it like the name says it packet mines the block, but most of the packet mines dont work most of the times on rotate servers, so i think it would be a cool idea if u could rotate while doing it so it would work on 2bpvp or on other rotate servers like 2b

**Additional info**  
ive seen just 1 client have it and its a private lient thats its still in development so i think it would be a cool idea

**Comment by TransRights** [comment]
This will be in 0.8
