### ISSUE TITLE
[FEATURE] L place and auto head place piston aura

### ISSUE THREAD

**Issue by HelpMopDog** [DarkiBoi/konas-issues#251]
### Title  
A short summary of the feature (no more than 10 words).
L place and auto head push
**Description**  
A detailed explanation of what this feature should be.
https://streamable.com/qm6nw3 Like this in the video so first L placing for piston aura would allow more spots for piston aura by just placing the redstone to either side and auto hade place would just be a addition to piston aura so if there auto trapped swording or somthing it would activate and start shoving the crystal above them into the block and auto break it dealing hella damage
**Additional info**  
Any other context or screenshots about the feature request.
https://streamable.com/qm6nw3

**Comment by ghost** [comment]
Very true. piston aura really needs some work rn

**Comment by TransRights** [comment]
0.8 will have a better pa placement algorithm
