### ISSUE TITLE
[FEATURE] disable surround when step enabled/chorusing

### ISSUE THREAD

**Issue by 3S0** [DarkiBoi/konas-issues#252]
### Title  
disable surround when step enabled/chorusing

**Description**  
I think there should be an option to disable surround automatically when I enable step, also when I chorus because most of the time I want to be strafing around after I chorus.

**Additional info**  
Any other context or screenshots about the feature request.

**Comment by timo-zzz** [comment]
I love this idea personally, but I think it would be even better to have a setting where you could instantly disable surrond upon the obby placing. Just an idea.

**Comment by Tux8068** [comment]
> I love this idea personally, but I think it would be even better to have a setting where you could instantly disable surrond upon the obby placing. Just an idea.

"togglable"

**Comment by TransRights** [comment]
Added in 0.8/9
