### ISSUE TITLE
[FEATURE] Double surround

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#253]
### Title  
Surround places 2nd layer.

**Description**  
Instead of making just surround it will do 2nd layer of it (to prevent faceplacers), if you hold the button. Make keybind you need to HOLD for surround to do double. (So you can pretty much press it once if you want surround and hold the same button for your surround to do double instead of 1 layer of it)

**Comment by iTwisten** [comment]
if people are faceplacing then just leave the hole

**Comment by TransRights** [comment]
Added in 0.8
