### ISSUE TITLE
Hotbarrrefill issue

### ISSUE THREAD

**Issue by NotJohnmcswag** [DarkiBoi/konas-issues#254]
hotbarrefill refilling is really weird, if a stack in your inventory is at 32 it wont take from that stack but from a different one so your inventory will start looking like this 
![](https://cdn.discordapp.com/attachments/782178169263489054/810568916690272286/unknown.png)

**Comment by DarkiBoi** [comment]
It takes from the biggest stack, I dont see how this is a bug

**Comment by TransRights** [comment]
Fixed in 0.9
