### ISSUE TITLE
[FEATURE] Irc 

### ISSUE THREAD

**Issue by 2147483647ms** [DarkiBoi/konas-issues#255]
Irc would allow konas users to talk to other konas users would also allow people to load a config from #config-sharing without downloading via .irc config load <name> .

Irc well its an irc though the config loading through irc would work where you request to load then it would just load [.irc] to talk to  other user [.irc config load] to load an irc config without downloading you see this feature in clients such as moon and astolfo

irc would display the uid of the person talking in () and irc would look like

IRC > 12x12 (000) hello!
irc would be colored light blue the uid would be pink or any color.

**Comment by iTwisten** [comment]
there is already one
its called konas chat
