### ISSUE TITLE
[FEATURE] Give konas an option to be installed as a versions folder.

### ISSUE THREAD

**Issue by 2147483647ms** [DarkiBoi/konas-issues#256]
Konas as a versions folder would pretty much eliminate other mods conflicting (could still be installed as a jar mod for forge).

Konas would have 2 downloads on the dashboard 1 the installer for the forge mod version the 2nd would download Konas.zip it would contain a read me on how to install (Unzip Konas.zip drag the folder into appdata/roaming/.minecraft/versions go into the minecraft launcher select a new version find konas pick konas change the amount of ram you want in jvm args then launch).

Having konas as a versions folder would pretty much stop people from no being able to use konas due to optifine other clients/mods ect.

This version of konas would also still contain an auto updater and all the other features just like the jar mod.

(The jar mod version of konas would still be installed the same way but in #faq you could say if the jar doesnt work at all use the versions folder)
Im not 100% sure if you could include optfine in the konas version as idk if its against the optifne eula.

**Comment by DarkiBoi** [comment]
What you are talking about is the Mod Coder Pack (MCP) which would require first of all rewriting konas for mcp and then maintaining two versions consecutively. No thanks
