### ISSUE TITLE
Ghast Notifier

### ISSUE THREAD

**Issue by lokumisadog** [DarkiBoi/konas-issues#257]
### Title  
Makes a sound and gives coords when dedects ghast.

**Description**  
Makes a sound when it detects a ghast and types the coords in chat but you can turn off either chat notifier or coords.

**Additional info**  
Nothing else

**Comment by iTwisten** [comment]
im guessing you want this for oldfag. i see how this could come in usefull

**Comment by lokumisadog** [comment]
> im guessing you want this for oldfag. i see how this could come in usefull

This is actually a feature on phobos, but I think it needs to be at basicly on all clients.

**Comment by TransRights** [comment]
Already in 0.8
