### ISSUE TITLE
[FEATURE] cancel cpacketplayer

### ISSUE THREAD

**Issue by Novola** [DarkiBoi/konas-issues#258]
### Title  
cpacketplayer cnaceled xploit

**Description**  
does the trollgod and cancel cp3fdtcketplayer

**Additional info**  
smely b a@lls

**Comment by Novola** [comment]
i NEed CpmcacekTplyarrt Cnacel AexlLOit

**Comment by Crystallinqq** [comment]
Kys

**Comment by DarkiBoi** [comment]
we already have packet canceller
