### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by Relbu** [DarkiBoi/konas-issues#261]
Add the module autohole (blink + baritone) for starters

Make a module called Bot which combines the modules autohole, autoburrow, autoholefill and autoeat into one. Upon death client would automaticall do /kit (insert kit name) and then drop into ffa (just walk 10 blocks forward and 10 to the side). 

Also would be awesome if you made it compatible with medal, so everytime you got a kill it would autoclip. So you can afk clips.

**Comment by TransRights** [comment]
🤨
