### ISSUE TITLE
 chams armor render[FEATURE]

### ISSUE THREAD

**Issue by iTwisten** [DarkiBoi/konas-issues#262]
### Title  
chams armor render option

**Description**  
There would be a option in chams where it renders the armor over players but still through walls

**Additional info**  
![2021-02-21_13 43 09](https://user-images.githubusercontent.com/77030212/108635018-d121fe80-744a-11eb-8c14-285536e58191.png)
This is what it would look like 
![2021-02-21_13 44 46](https://user-images.githubusercontent.com/77030212/108635066-09294180-744b-11eb-8c5a-f0f10073d365.png)

this is what it looks like now

**Comment by TransRights** [comment]
You can do this with the 0.9 chams rewrite
