### ISSUE TITLE
Piston Aura Updates

### ISSUE THREAD

**Issue by Lempity** [DarkiBoi/konas-issues#265]
### Title  
A short summary of the feature (no more than 10 words).
Option to Auto Turn off piston aura if cant place and also tell why can't place, like gamesense
**Description**  
A detailed explanation of what this feature should be.
There would be a option for turning of piston aura if no target/can't place. Chat notifs like: Placing, Can't Place because of XYZ. And also piston esp would show when someone could be pistoned.
**Additional info**  
Any other context or screenshots about the feature request.

**Comment by TransRights** [comment]
Added in 0.9.2
