### ISSUE TITLE
 note bot[FEATURE]

### ISSUE THREAD

**Issue by iTwisten** [DarkiBoi/konas-issues#266]
with notebot no longer will people buy future

**Comment by ghost** [comment]
You also have to rely on community, that gonna make songs, which konas... doesn't have. (even from your response you gave me you can understand what kind of community there's in konas)
Also they have to either get full code of Future's notebot and make it use the same .notebot file and work exactly the same or they have to make new one, which is where community problem comes. Ppl in future used to make a lot of songs, and I made some. Konas is literally 12yo kids who want to cpvp. So.... Notebot with no songs? Sounds good!!

**Comment by TransRights** [comment]
Notebot is a public mod, you don't need future to use it
