### ISSUE TITLE
Faceplace Toggle Option

### ISSUE THREAD

**Issue by MonkeLivesMatter** [DarkiBoi/konas-issues#27]
Add faceplace toggle to deal with annoying holefags and scrollable gui so people don't need to set their gui scale to the small

**Comment by DarkiBoi** [comment]
first of all please read the guide on how to title your tickets, and second of all the new gui is already in the works

**Comment by very-cashmoney** [comment]
the lethalmultiplier option is the equivalent of faceplace. if ur crystal is going to deal 2 damage, and the enemy has 8 hp; ur lethal multiplier should be at 4. but u can just have it at 10 so itll faceplace everytime

**Comment by zyktex** [comment]
You can do this with macros
