### ISSUE TITLE
Auto obby 

### ISSUE THREAD

**Issue by luapwastaken** [DarkiBoi/konas-issues#271]
### Title  
Auto obby randomly Stops working

**Description**  
After about 20-30 echests ( or even less) mined it stops working even After relog or moving 

**Steps to reproduce:**  
2. Toggle auto obby module
4. Experience  bug

**Additional info**  
OS:Windows 10, java version:newest , client version: 1.12.2

**Comment by TransRights** [comment]
Unable to replicate

**Comment by luapwastaken** [comment]
> Unable to replicate

was patched 2 updates ago this is a old post
