### ISSUE TITLE
[BUG] wierd Yaw fix in inventory 

### ISSUE THREAD

**Issue by luapwastaken** [DarkiBoi/konas-issues#273]
**Description**
When i open my inventory my yaw is always fixed to look south 

**Steps to reproduce:**  
1. Open inventory 
2. Toggle none
4. Experience example bug

**Screenshots:**  
Not on my pc atm can send Screenshot in discord when i am (Luap#9393)

**Additional info**  
Add any other useful information. For example: OS:windows 10, java version: newest, client version:1.12.2
 
edit: screenshot link https://gyazo.com/abe8e2f3102ef2e71d8df8aefa809261

**Comment by TransRights** [comment]
Duplicate
