### ISSUE TITLE
A Bindlist

### ISSUE THREAD

**Issue by Beraugwastaken** [DarkiBoi/konas-issues#274]
### Title  
A list that shows the bindings you have to each module

**Description**  
A Hud thing that shows what your binding is for the modules you have a binding for

**Additional info**  
They got one in rusher that look like this 
![image](https://user-images.githubusercontent.com/79546317/108915284-f1111800-762c-11eb-8d74-919a0f1eb5ab.png)

**Comment by very-cashmoney** [comment]
dot modules

**Comment by Beraugwastaken** [comment]
Is that only a feature in beta because i can't find it in my client

**Comment by iTwisten** [comment]
> dot modules

dont think ive ever seen that either

**Comment by DarkiBoi** [comment]
.modules it has been there since b1

**Comment by Beraugwastaken** [comment]
the thing i wanted it as was as an hud feature, i don't know if that is possible

**Comment by DarkiBoi** [comment]
It is but I dont see how that is useful if you just have the .modules command? I dont know why you need a constant reminder for what you have bound to what
