### ISSUE TITLE
[FEATURE] Packet Swing Module

### ISSUE THREAD

**Issue by Alphazs** [DarkiBoi/konas-issues#277]
### Title  
Packet Swing module, makes it so it makes 1.8 animations instead of 1.12.2

**Description**  
make it a render module that makes the 1.8 swing so ur gapps wont drop down when ur crystalling or ur sword when ur swording

**Additional info**  
it would be a pretty good render module imo

**Comment by RafPvper** [comment]
OldAnimations feature in render or misc it alr exists
