### ISSUE TITLE
[BUG] CA attacks freecam entity of other clients

### ISSUE THREAD

**Issue by hashalite** [DarkiBoi/konas-issues#279]
### CA attacks freecam entity of other clients

**Description**  
When using Rusherhack's freecam, Konas' CA attacks your own player.  John says that it can be fixed by avoiding targeting instances of EntityPlayerSP.

**Steps to reproduce:**  
1. Enable CrystalAura
2. Enable freecam in a separate client

**Comment by lokumisadog** [comment]
I dont think this is patchable but you can try to friend yourself

**Comment by hashalite** [comment]
Konas does not allow you to friend yourself.  I also gave a possible solution in the report.

**Comment by RafPvper** [comment]
.friend add insertyournamehere

**Comment by twentyfived2** [comment]
Of course it's going to target your freecam. It thinks it's another player. Use konas' freecam and friend yourself. Or just turn CA off when going to free cam

**Comment by hashalite** [comment]
Once again, Konas does not allow you to friend yourself.  It literally tells you “You cannot friend yourself” when you try.  And if you read my report, you would know it is patchable by ignoring EntityPlayerSP.

**Comment by 3jq** [comment]
Its patchable if you will add something like mc.player.getName and if(TargetEntityName = mc.player.getName) it will get fixed lol, ez patch

**Comment by 3jq** [comment]
Like that, I took that from gamesense entity util, literally ez patch.

public static boolean basicChecksEntity(Entity pl) {
		return pl.getName().equals(mc.player.getName());
	}

**Comment by TransRights** [comment]
Don't use clients with 2018 freecams. Simple
