### ISSUE TITLE
[BUG] Capes bug

### ISSUE THREAD

**Issue by CherkaSSH** [DarkiBoi/konas-issues#280]
Can’t use capes(module in Konas)

**Description**  
Idk y when a guy with optifine cape and Konas user cape shows up my FPS drops to 7(CPU AMD ryzen 5 Graphics card is GeForce RTX 2070 so usually 150 fps)

**Steps to reproduce:**  
1. Open GUI
2. Toggle Capes
3. Load guy with optifine and Konas cape 
4.Done 

**Screenshots:**
(can’t give bec I’m from a phone rn)

**Additional info**  
Win 10 last Java

**Comment by DarkiBoi** [comment]
Can you tell me if this bug still persists
