### ISSUE TITLE
[FEATURE] Timer boost scaffold

### ISSUE THREAD

**Issue by 2147483647ms** [DarkiBoi/konas-issues#282]
Timer boost scaffold would enable timer 1.5782 when towering up.

it would be just something you toggle in scaffold as it doesn't bypass 2b and constantium.

**Comment by lokumisadog** [comment]
I dont think this would work but you should give it a try yourself

**Comment by iTwisten** [comment]
if you need it then you cant bind scaffold and timer to the same key. also to get timer to exactly 1.5782 you can use the command .set timer factor 1.5782

**Comment by 2147483647ms** [comment]
> I dont think this would work but you should give it a try yourself

Works on most servers

**Comment by TransRights** [comment]
Added in 0.9.2
