### ISSUE TITLE
[BUG] BedAura Does not place in 2 block holes (while the player is on the the second block )

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#283]
### Title  
well the main reason we use bedaura is to break city traps and place beds in 2 block holes , but the bedaura does not do that 

**Description**  
title

**Steps to reproduce:**  
1. Spawn A fake player in a 2 block hole (the fakeplayer should be on one block at a side)
2. turn on bedaura
3. it will not place

**Screenshots:**  
If applicable, add screenshots to show the issue.

**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by iTwisten** [comment]
you want it to were if there is a 2 block hole and the player is in 1 it will like place the bed in them. that not possible man. because the players hitbox obstructs the 2 block you need to place a bed.
