### ISSUE TITLE
[BUG] please remove all among us references

### ISSUE THREAD

**Issue by kars0nn** [DarkiBoi/konas-issues#287]
### Title  
A short summary of the bug (no more than 10 words).

**Description**  
A clear description the bug.

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
If applicable, add screenshots to show the issue.

**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by DarkiBoi** [comment]
:trollface:
