### ISSUE TITLE
Offhand Swing

### ISSUE THREAD

**Issue by NotJohnmcswag** [DarkiBoi/konas-issues#30]
Add an offhand swing that will swing with offhand even when you're just regularly hitting (DONT FUCKING DELETE THIS SUGGESTION OR UR GAY)

**Comment by very-cashmoney** [comment]
it already exists you fockhing retard it swings with the hand you have the crystal on

**Comment by zyktex** [comment]
Ok well add that option to swing

**Comment by NotJohnmcswag** [comment]
yes this
