### ISSUE TITLE
[FEATURE] SuperheroFX

### ISSUE THREAD

**Issue by nukiz** [DarkiBoi/konas-issues#305]
### Title  
A short summary of the feature (no more than 10 words). Module that shows "Bang", "Boom" "Oof" or something like that when you deal damage

**Description**  
A detailed explanation of what this feature should be.
Module that shows attack indicators like in older comic books, like Superman/Spiderman.

 This module should also have 2 settings, 'Damage' and 'Comic'. Damage would show damage dealt instead of something like pow or smash. Comic would show pow, smash etc.

**Additional info**  
Any other context or screenshots about the feature request.
This module is in Pyro and ZeroDay, watchibg any video regarding zeroday will show you the effect.

**Comment by iTwisten** [comment]
yeahh
we need this

**Comment by DarkiBoi** [comment]
Damage dealt mode is already in CA and superhero FX is just cringe
