### ISSUE TITLE
[FEATURE] Pre-Made configs / just a tab where u load / save configs etc.

### ISSUE THREAD

**Issue by scaffoldd** [DarkiBoi/konas-issues#308]
A Tab or smthin where u can go on Konas discord and upload ur Configs from maybe a Configs folder in konas and u can upload ur configs.

and the pre-made configs are like configs where u get like servers like cpvp.cc 2bpvp etc already pre-made configs and devs can make them unpatched if they do get patched some how idk like every konas update they could update the pre made configs if they want.

**Comment by TransRights** [comment]
80% of settings are up to personal preferences. There is maybe a total of 30 settings in the entire client which are server specific; therefore, this is mostly useless.
