### ISSUE TITLE
[BUG] autotrap rotation kick

### ISSUE THREAD

**Issue by SoggyBacco** [DarkiBoi/konas-issues#309]
autotraps rotations gets u kicked on the latest ncp

**Description**  
if u use autotrap with rotate on the newest ncp build u get kicked for invalid rotations

**Steps to reproduce:**  
1. join server with the latest ncp version (ex: meteorpvp, ecme, ect)
2. turn on rotate for autotrap
3. autotrap someone
4. get kicked for invalid rotations

**Comment by TransRights** [comment]
Fixed in 0.9.1
