### ISSUE TITLE
Add a way for users to request an HWID reset.

### ISSUE THREAD

**Issue by Wallace1020** [DarkiBoi/konas-issues#310]
I recently bought a new computer so that I wouldn't have to play on the unplayably slow one I was using before, and while trying to download Konas client onto my new computer, I found that my HWID didn't match. I needed to request an HWID reset, but I didn't know where to ask, I looked at the site for a forum, and I looked at the discord to see if I was supposed to ask there, but my attempts to find a way to request an HWID reset were unsuccessful. Please reset my HWID, I payed once for this client no less than 2 weeks ago. My Konas account is "Wallace1020".

If this was the wrong place to ask please tell me where I am supposed to ask this.

**Comment by DarkiBoi** [comment]
One question "How do I reset my hwid" in the discord server would have been enough for the bot to give you an automated answer. When in doubt always dm me

**Comment by Wallace1020** [comment]
![#announcements - Discord 4_3_2021 9_40_00 AM](https://user-images.githubusercontent.com/81846342/113483468-c5b9ee00-9460-11eb-8ac9-87a2388ae203.png)
Sorry, but I only have announcements and vc showing on my screen.

**Comment by Wallace1020** [comment]
![#announcements - Discord 4_3_2021 9_40_00 AM (2)](https://user-images.githubusercontent.com/81846342/113483498-f8fc7d00-9460-11eb-9ebf-856e760c664e.png)
Sorry, but I only have announcements and vc showing on my screen.
