### ISSUE TITLE
[FEATURE] CA Update

### ISSUE THREAD

**Issue by notbada** [DarkiBoi/konas-issues#311]
I feel like CA could use an update, I see other people CAs being a lot faster than mine with relatively same ping, also I feel like older versions of Konas had faster CAs (that's maybe why I feel like it's slow now compared to others, it may be just outdated).

**Comment by iTwisten** [comment]
ca is good just get a decent config

**Comment by 2147483647ms** [comment]
> ca is good just get a decent config

large true

**Comment by ignHamoude** [comment]
no i actually can understand, it was faster before

**Comment by twentyfived2** [comment]
It was not faster before. If u don't like the new ca. Dont use it
