### ISSUE TITLE
[BUG] Konas NoFall doesnt work

### ISSUE THREAD

**Issue by Fyrex0** [DarkiBoi/konas-issues#314]
Konas NoFall doesnt work

**Comment by iTwisten** [comment]
doesnt work on some server prob got patched

**Comment by s0daa** [comment]
Config issue or its patched on the server

**Comment by Fyrex0** [comment]
mode packet not working

**Comment by Fyrex0** [comment]
> Config issue or its patched on the server
Mode packet not working -_-

**Comment by s0daa** [comment]
> > Config issue or its patched on the server
> 
> Mode packet not working -_-
> 
> 

what server
