### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pommmmm** [DarkiBoi/konas-issues#315]
add a module to load inventory presets from shulkers. For example create a preset for your inventory after kitting up so it know what you want your inventory to look like. If you turn the module on it will look in shulkers for items that can fit the preset and move it into the correct inventory spot. This could speed up re-gearing or kitting up to get into pvp. Example: you just died and need to get back into fight quickly- you get the shulkers out of your e chest and put it down, toggle the module, and it automatically takes the items from your shulkers and puts it in your inventory how you want it.

**Comment by iTwisten** [comment]
like re gear rhack has

**Comment by ignHamoude** [comment]
yea i think so, but this a requirement to get on konas, itd be very useful

**Comment by TransRights** [comment]
Duplicate
