### ISSUE TITLE
Elytra-Prior[BUG]

### ISSUE THREAD

**Issue by Organik-cmd** [DarkiBoi/konas-issues#319]
### Title  
A short summary of the bug (no more than 10 words).
I found a bug that crashes Konas over and over
**Description**  
A clear description the bug.
If I enable elytra prior on auto auto armor inside lava, it makes my Konas to crash and it makes imposible to join any game (singleplayer too). To disable this bug you need to go to konas archive and desable auto armor.
**Steps to reproduce:**  
1. Be in lava
2.  Open click GUI
3. enable elytra prior while having elytra fly on mode creative
4. experience de bug.

**Additional info**  
Add any other useful information. For example: OS --> windows 10, java version last one, client version 0.8.2.
I have the crash report on a Ubuntu pastebin.

**Comment by TransRights** [comment]
I am unable to replicate this, please open a ticket in the discord and send your crash log there.
