### ISSUE TITLE
[FEATURE] Manual Password Reset

### ISSUE THREAD

**Issue by PythonJoshua** [DarkiBoi/konas-issues#321]
### Title  
Password Reset

**Description**  
I think users should be able to reset their passwords manually if they forgot their password and can't login, maybe you put your License key to get a reset then you enter your new password. (For both dashboard and installer.)

**Additional info**  
No other context

**Comment by iTwisten** [comment]
i dont think anyone keeps their license key

**Comment by twentyfived2** [comment]
This is not allowed for security reasons

**Comment by PythonJoshua** [comment]
> i dont think anyone keeps their license key
> 
> 

It's in peoples emails it's easy to access you can just search for keywords on gmail or iCloud etc
