### ISSUE TITLE
[FEATURE] ShulkerMiner for BlockAura

### ISSUE THREAD

**Issue by Leaor** [DarkiBoi/konas-issues#324]
### Shulker yoink 
A short summary of the feature (no more than 10 words).

**Description**  
Shulker yoink will destroy every shulker in your render distance. I think it's a cool feature that should be added to the client

**Additional info**  
None.

**Comment by Leaor** [comment]
Honestly this would be a cool feature

**Comment by twentyfived2** [comment]
This is completely useless

**Comment by TransRights** [comment]
Duplicate
