### ISSUE TITLE
RightClick Gap[BUG]

### ISSUE THREAD

**Issue by Zxmon-code** [DarkiBoi/konas-issues#327]
The RightClick Gap function in Offhand doesnt work

when you activate RightClick Gap and try to use it it does nothing

1. Open Clickgui
2. Open Offhand options
3. Activate Gapple
4. Activate RightClickGap
5. Toggle Offhand
6. Close Clickgui
7. RightClick
8. realise that it doesnt work

![2021-04-14_09 03 27](https://user-images.githubusercontent.com/68187602/114668063-95940a00-9d00-11eb-83e2-78aa127e2256.png)
![2021-04-14_09 03 42](https://user-images.githubusercontent.com/68187602/114668068-962ca080-9d00-11eb-8376-97dc46d94ed0.png)
![2021-04-14_09 04 29](https://user-images.githubusercontent.com/68187602/114668070-96c53700-9d00-11eb-989a-5953c2476ef7.png)
![2021-04-14_09 04 37](https://user-images.githubusercontent.com/68187602/114668071-96c53700-9d00-11eb-8592-f8401edbce7a.png)

**Comment by iTwisten** [comment]
i think its right click gap on sword only

**Comment by UltimateBoi** [comment]
Could you send your config and pack pls, ur gui looks sick af

**Comment by Zxmon-code** [comment]
[Config.zip](https://github.com/DarkiBoi/konas-issues/files/6390007/Config.zip)
This is one of the packs: https://www.mediafire.com/file/606jkamqy1233yz/Rose_Aura_Release_v0.1.1.zip/file
And this is the one with base textures: https://www.mediafire.com/file/rdj1k27vfokjge6/%2521%25C2%25A7_Vertic_%25C2%25A7716x.zip/file

**Comment by Zxmon-code** [comment]
> Could you send your config and pack pls, ur gui looks sick af

Config.zip
This is one of the packs: https://www.mediafire.com/file/606jkamqy1233yz/Rose_Aura_Release_v0.1.1.zip/file
And this is the one with base textures: https://www.mediafire.com/file/rdj1k27vfokjge6/%2521%25C2%25A7_Vertic_%25C2%25A7716x.zip/file

**Comment by UltimateBoi** [comment]
Thanks

**Comment by DarkiBoi** [comment]
> i think its right click gap on sword only

yes rightclick gap is meant for when you are holding a sword
