### ISSUE TITLE
[機能]Cevbreaker

### ISSUE THREAD

**Issue by 131311313** [DarkiBoi/konas-issues#331]
### Cevbreaker

**Description**  
This function places obsidian above the enemy's head, places a crystal there, breaks the obsidian, and breaks the crystal. 
This can do a lot of damage and is a great motivator for cpvp!

As you can see in gamesense, if you have cevbreaker in konas, you will be the best client in the world!

**Additional info**  

It is a feature that will only become stronger when it is compatible with fastbreak :D

**Comment by DaisyD2** [comment]
speedmine, there is a mode called instant break, the crystal setting will place a crystal, smart mode in ca will break it when it does damage, keeping autotrap on will replace the block and start the cycle again, this was in konas before gsense

**Comment by iTwisten** [comment]
> speedmine, there is a mode called instant break, the crystal setting will place a crystal, smart mode in ca will break it when it does damage, keeping autotrap on will replace the block and start the cycle again, this was in konas before gsense

i think he wants it all in one module

**Comment by oscar269** [comment]
The three hack method overwhelms the key bindings and is not stable.

**Comment by twentyfived2** [comment]
No

**Comment by DarkiBoi** [comment]
speedmine, there is a mode called instant break, the crystal setting will place a crystal, smart mode in ca will break it when it does damage, keeping autotrap on will replace the block and start the cycle again, this was in konas before gsense
