### ISSUE TITLE
[BUG] Speed Bug for some reason at random times my fps drops and shows like i am flying is like long jump but faster and drops ur fps sometimes crash ur game

### ISSUE THREAD

**Issue by FaxHack** [DarkiBoi/konas-issues#332]
### Title  
A short summary of the bug (no more than 10 words).

**Description**  
[BUG] Speed Bug for some reason at random times my fps drops and shows like i am flying is like long jump but faster and drops ur fps sometimes crash ur game

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
If applicable, add screenshots to show the issue.

**Additional info**  
[BUG] Speed Bug for some reason at random times my fps drops and shows like i am flying is like long jump but faster and drops ur fps sometimes crash ur game
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by DarkiBoi** [comment]
Please follow the template correctly
