### ISSUE TITLE
[BUG] Holefill dum

### ISSUE THREAD

**Issue by RafPvper** [DarkiBoi/konas-issues#334]
Smart Holefill problem 
Smart holefill sees self as enemy

When using the new rewritten smart holefill 
It counts the player itself as an enemy so it's constantly hole filling the person using it
Edit : DisableWhenNone also doesnt work
sad 

**Steps to reproduce:**  
1. Open GUI 
2. Toggle holefill with smart mode on
3. Now go near any hole with no other player nearby 
4. And you end up hole filling yourself even if you managed to add yourself It will still holefill you and people in ur friends list (I think not sure)

**Comment by DarkiBoi** [comment]
HoleFill does not target yourself as an enemy, please read the setting description in the changelog
