### ISSUE TITLE
[FEATURE] AntiBurrow

### ISSUE THREAD

**Issue by batteryboi2** [DarkiBoi/konas-issues#335]
Modify anti surround and auto anvil to make an anti burrow that mines out a burrow and places a pressure plate under the opponent preventing burrowing.

**Comment by batteryboi2** [comment]
This might also be possible with buttons?

**Comment by iTwisten** [comment]
you cant place a pressure plate under someone

**Comment by MegaGamer0024** [comment]
> you cant place a pressure plate under someone

yes you can lol

**Comment by twentyfived2** [comment]
There is already an anti burrow in the client. Its in the piston aura
