### ISSUE TITLE
CrystalAura breaking issues

### ISSUE THREAD

**Issue by MegaGamer0024** [DarkiBoi/konas-issues#336]
the 0.9 update removed the crystal break damage setting, This is an issue because if the target is moving it will end up having big issues with breaking, and end up multiplacing a lot.  (160 ms, constantiam.net)

**Comment by twentyfived2** [comment]
The ca works fine on const for me. All CAs are not that good when chasing, that's just constantiam for you

**Comment by DarkiBoi** [comment]
Use the Security Setting to customize max self damage to enemy damage ratio when breaking enemies crystals
