### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#339]
### Title   
hud elements moving very time i restart my game

**Description**  
fps ping tps and speed move every time i restart my game

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
![image](https://user-images.githubusercontent.com/72751613/115963837-71ff6980-a521-11eb-8074-60572b414a62.png)

**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by UltimateBoi** [comment]
Probably config issue ngl

**Comment by DarkiBoi** [comment]
Fixed in 0.9.1

**Comment by UltimateBoi** [comment]
Pog!
