### ISSUE TITLE
[FEATURE] Server Type Hud (Spigot, Vanilla, Paper e.t.c)

### ISSUE THREAD

**Issue by UltimateBoi** [DarkiBoi/konas-issues#341]
### Server Type (like spigot, Paper, vanilla e.t.c.)

**Could you add it to the hud features**  

**None really, its quite simple. Just like kami blue (rip) go on kami blue and turn on server type or something in hud editor, basically that!**

**Comment by twentyfived2** [comment]
I don't see how it's useful

**Comment by UltimateBoi** [comment]
so i can find certain things like dupes for that specific server type

**Comment by TransRights** [comment]
Added in 0.9.2

**Comment by UltimateBoi** [comment]
POggg
