### ISSUE TITLE
[BUG] Damages on CA Don't work

### ISSUE THREAD

**Issue by UltimateBoi** [DarkiBoi/konas-issues#342]
### Damages on CA don't work

**I set faceplace hp to 10 and it was faceplacing at 30 hp on my friend**  

**Steps to reproduce:**  
Turn damage to 1, starts faceplacing at 30 hp

**Screenshots:**  
none

**Additional info**  
Java, forge latest version
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.
it dosnet cause a crash

**Comment by twentyfived2** [comment]
This isn't a ca damage issue. You have min damage to 1 and faceplacing can do equal or over 1 damage to the target so it will place there. Turn up min damage to solve this
