### ISSUE TITLE
[FEATURE] pickaxe spoof

### ISSUE THREAD

**Issue by iTwisten** [DarkiBoi/konas-issues#345]
### Title  
add pickaxe spoof to packet mine

**Description**  
spoofs pickaxe so you can click with any item in hotbar and it will mine with pickaxe. you do need to have a pickaxe in your hotbar
**Additional info**  
auto mod has it

**Comment by DarkiBoi** [comment]
Thats impossible

**Comment by iTwisten** [comment]
but its not auto mod does it its called mining spoof

**Comment by luapwastaken** [comment]
> but its not auto mod does it its called mining spoof
> 

It doesnt work well and is pretty useless
