### ISSUE TITLE
Add notebot [FEATURE]

### ISSUE THREAD

**Issue by Eonexe** [DarkiBoi/konas-issues#359]
### NoteBot
A short summary of the feature (no more than 10 words).

**A module that automatically plays noteblocks, similar to futures or phobos'**  
A detailed explanation of what this feature should be.

**balls**  
Any other context or screenshots about the feature request.

**Comment by Droid-D3V** [comment]
YES, ADD THIS PLEASE

**Comment by JessSystemV** [comment]
This would be awesome, i wouldn't have to keep **future** on standby for just notebot.
