### ISSUE TITLE
[FEATURE]MultiThread for ca and offhand

### ISSUE THREAD

**Issue by CandyCat1029** [DarkiBoi/konas-issues#363]
Put ca and offhand on another thread so it will decrease the load on the main render and runtick thread

**Comment by CandyCat1029** [comment]
multithread delay stuff for a bit but at least much less fps drop cuz minecraft is single core based

**Comment by ghost** [comment]
What makes you think this isn’t already a thing?

**Comment by TransRights** [comment]
No, that's stupid and useless
