### ISSUE TITLE
Pingbypass Ca

### ISSUE THREAD

**Issue by VikasLagerweij** [DarkiBoi/konas-issues#367]
just make like a pingbypass tab in the clickgui which only activated when you have entered a proxy-ip and port in the multiplayer screen and then add a ca to the tab. try looking into the pingbypass 1.0.0 code might help or smth i hope this gets added i begg u daddy darki

**Comment by TransRights** [comment]
PingBypass works by having AutoCrystal run on a VPS, so no.
