### ISSUE TITLE
issue with crystal aura

### ISSUE THREAD

**Issue by Tux8068** [DarkiBoi/konas-issues#37]
rotations become bugged while using crystal aura. i think its with swing packet

**Comment by zyktex** [comment]
Perhaps you have noswing on? Could you please elaborate on what you mean by rotations becoming bugged

**Comment by Tux8068** [comment]
yes, my rotations sperg out moving very strange directions, not allowing me to exp

**Comment by zyktex** [comment]
You cant xp while crystalling, obviously. Wait 350ms or more after placing/breaking your last crystal before starting to mend. There were other bugs involving rotations but those have been fixed aswell
