### ISSUE TITLE
option to change the image for the logo[FEATURE]

### ISSUE THREAD

**Issue by moaihax** [DarkiBoi/konas-issues#373]
### Title  
add something in the file options like the way to change the auto ez so that you can change the konas k

**Description**  
in the file for konas their should be a folder to put images and have them as the watermark then you in game would be able to select wich one through a menu or a command and maybe it could come default with a few options like  a cute colour k

**Additional info**  
Any other context or screenshots about the feature request.

**Comment by luapwastaken** [comment]
> ### Title
> add something in the file options like the way to change the auto ez so that you can change the konas k
> 
> **Description**
> in the file for konas their should be a folder to put images and have them as the watermark then you in game would be able to select wich one through a menu or a command and maybe it could come default with a few options like a cute colour k
> 
> **Additional info**
> Any other context or screenshots about the feature request.

Good idea maybe a color picker instead of a folder  or just the cute version for normal access and for boosters and beta the custom logos :3

**Comment by TransRights** [comment]
You can already do this using a texturepack (minecraft/konas/textures/konas.png)
