### ISSUE TITLE
[BUG] Speed&burrow 

### ISSUE THREAD

**Issue by jj-inc** [DarkiBoi/konas-issues#379]
### Speed&burrow bag  

**Description**  
When i place block under me(burrow, rubber fill) and turn on speed(strafe mod) i get rubber band and i cant leave from burrow

**Comment by jj-inc** [comment]
i tried at cpvp.cc and 2bpvp, so i get rubber band in 100%

**Comment by TransRights** [comment]
How is this a bug?
