### ISSUE TITLE
[BUG] aarch64(?) incompatibility

### ISSUE THREAD

**Issue by DerpoDrago** [DarkiBoi/konas-issues#385]
### Title  
aarch64(?) mixin loading error

**Description**  
Konas will not load on aarch64 operating systems (might be other issue)

**Steps to reproduce:**  
1. Put Konas in mods folder
2. Load forge
3. Nothing (not even the Mojang loading screen) appears

**Additional info**  
Java version: OpenJDK 64-Bit Server VM, version 1.8.0-internal
Forge Version: 14.23.5.2855

**Comment by ghost** [comment]
That is not an architecture issue, I use konas on an arm machine and it works fine. Most likely a gpu issue.
