### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ignHamoude** [DarkiBoi/konas-issues#390]
### Title  
fly in render glitch

**Description**  
so sometimes while i turn on speed with strafe, eat something and at the same time move left or right and i go very fast(in render) and my game crashes

**Steps to reproduce:**  
1. turn on speed with strafe
2. Teat something ingame
3. move left or right
4. fly render

**Additional info**  
java 8

**Comment by luapwastaken** [comment]
not a konas issue. other client being chinese :3

**Comment by TransRights** [comment]
> not a konas issue. other client being chinese :3

yeah
