### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ignHamoude** [DarkiBoi/konas-issues#391]
### Title  
auto gear

**Description**  
turn on auto gear and open a shulker and itll put the items in your inventory in the selected spots

**Additional info**  
you make a command with it to save your items slots

**Comment by pommmmm** [comment]
Already in gamesense client, I recommend using gamesense and konas if you think you would use this often. Here’s a video demonstrating it https://youtu.be/dG85SkH6Zvw

**Comment by TransRights** [comment]
Duplicate of #263
