### ISSUE TITLE
[BUG] Raytrace not working

### ISSUE THREAD

**Issue by scaredcr6w** [DarkiBoi/konas-issues#395]
### Title  
Raytrace not working

**Description**  
Raytrace doesn't work if the target is between the player and the crystal.

**Steps to reproduce:**  
1. Turn on raytrace
2. Put a FakePlayer in between the player and the target
3. Turn on AutoCrystal
4. Experience bug

**Screenshots:**  

https://user-images.githubusercontent.com/85457088/120937472-e5de8580-c70d-11eb-8af1-736ed872d168.mp4

**Additional info**  
Minecraft ver: 1.12.2
Konas ver: 0.9.1

**Comment by luapwastaken** [comment]
> ### Title
> Raytrace not working
> 
> **Description**
> Raytrace doesn't work if the target is between the player and the crystal.
> 
> **Steps to reproduce:**
> 
> 1. Turn on raytrace
> 2. Put a FakePlayer in between the player and the target
> 3. Turn on AutoCrystal
> 4. Experience bug
> 
> **Screenshots:**
> 
>  raytrace-bugreport.mp4 
> **Additional info**
> Minecraft ver: 1.12.2
> Konas ver: 0.9.1

looks like a desync or config issue this doesnt happen to me check the config server for help and watch the ca tutorial video
