### ISSUE TITLE
[BUG] 1.17 Protocol

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#397]
### 1.17 Protocol
A short summary of the bug (no more than 10 words). 1.17 Protocol

**Description**  
A clear description the bug.
The 1.17 protocol does not work on the 1.17 servers I have tested it on. I tested it out on 3 diffrent vanila 1.17 servers and did not get in on any of them. 

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
If applicable, add screenshots to show the issue. https://ibb.co/GW5C0ZX 

**Additional info**  
Add any other useful information. For example: OS, java version, client version. 
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by iTwisten** [comment]
as of rn via version is on a snapshot of 1.17
and not the full release
you cant join any servers untill viaversion updates
