### ISSUE TITLE
[BUG] This client is dog shit

### ISSUE THREAD

**Issue by ghost** [DarkiBoi/konas-issues#407]
### Title  
A short summary of the bug (no more than 10 words).

**Description**  
A clear description the bug.
This Client Is A "Paste"
**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug

**Screenshots:**  
If applicable, add screenshots to show the issue.

**Additional info**  
Add any other useful information. For example: OS, java version, client version.
 
**⚠️ Disclaimer:** If this bug causes a crash, please save your crash report so, if asked, you can provide it to help us fix the issue.  
Please do **NOT** paste or upload them to this github.

**Comment by ghost** [comment]
Please shut down This mess for god sake!

**Comment by ghost** [comment]
Exit scam

**Comment by ghost** [comment]
Still an exit scam

**Comment by Twelve0001** [comment]
got updated 6 days ago, no idea what you are talking about

**Comment by ghost** [comment]
who the fuck are you nonamer

**Comment by northskies** [comment]
ur retarded lmfao
