### ISSUE TITLE
phobos 1.5.4 compatibility

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#41]
make konas compatible with phobos 1.5.4

**Comment by zyktex** [comment]
Send your crash log please

**Comment by DachaBager** [comment]
ERROR
Game crashed
An unexpected issue occured and the game has crashed. We're sorry for thhe inconvenience.


there is no crash log its just this

**Comment by Crystallinqq** [comment]
Suck my balls

**Comment by DachaBager** [comment]
kek

**Comment by KohimaNayagato** [comment]
ur retarded "theres no crash log"

HOW TO NOT BE A RETARD
press windows + r
type %appdata%\.minecraft\logs
press enter
send this little file called latest.log
CONGRATULATIONS you are no longer retarded

**Comment by DarkiBoi** [comment]
@zyktex Already on the trello with full bug report 🙄

**Comment by DachaBager** [comment]
[latest.log](https://github.com/DarkiBoi/konas-issues/files/5404344/latest.log)
[debug.log](https://github.com/DarkiBoi/konas-issues/files/5404345/debug.log)

**Comment by Katatje** [comment]
We still need this

**Comment by DarkiBoi** [comment]
Fixed, also stop using rats, thanks

**Comment by very-cashmoney** [comment]
> Fixed, also stop using rats, thanks

it isnt a rat what do you mean

**Comment by ghost** [comment]
truth

**Comment by ddke1** [comment]
> We still need this

U a bitch nigga
