### ISSUE TITLE
Speed bind [BUG]

### ISSUE THREAD

**Issue by Tr0llMode** [DarkiBoi/konas-issues#426]
### Title  
Speed works without bind.

**Description**  
I deleted speed bind, but when i click the button where bind has been, speed turns on. Idk how to explain this.

**Steps to reproduce:**  
1. Open example GUI
2. Toggle example module
3. Press example key
4. Experience example bug
![image](https://user-images.githubusercontent.com/88204047/132121364-79e81c46-233f-46ec-8702-56bcc5792725.png)

**Screenshots:**  

**Additional info**  
last version, windows 10, i use future + konas + wp3.

**Comment by TransRights** [comment]
You still have speed bound to SUBTRACT in the screenshot you provided.
