### ISSUE TITLE
Killaura Suggestion

### ISSUE THREAD

**Issue by NotJohnmcswag** [DarkiBoi/konas-issues#43]
For Aura make rotations stay on the target, like how future does it instead of what it does now which is snap on the target for a short amount of time. If it stayed on the target it would get less lagbacks

**Comment by zyktex** [comment]
No, it would cause more lagbacks, and no, future doesn't do that. But yes, we'll add this.

**Comment by NotJohnmcswag** [comment]
Yes future does do that, with aura it isnt a snap it stays on the target
