### ISSUE TITLE
CrystalAura additions suggestions

### ISSUE THREAD

**Issue by BNawesome** [DarkiBoi/konas-issues#45]
I think crystal aura should have stop while mining, stop while eating, and stop when below a certain health. There are also some other bugs with the ca just randomly stopping.

**Comment by zyktex** [comment]
Stop below certain health is antisuicide. Stop while eating is nogapswitch. We'll implement nomineswtich aswell than ig

**Comment by DarkiBoi** [comment]
Also please read the guide on how to name your issues properly

**Comment by very-cashmoney** [comment]
smol

**Comment by very-cashmoney** [comment]
brain

**Comment by zyktex** [comment]
StopWhileMining has already been implemented
