### ISSUE TITLE
module idea (anticoordleak)

### ISSUE THREAD

**Issue by Tux8068** [DarkiBoi/konas-issues#54]
have a "anticoordleak" chat module, basically when you type coord-like numbers in chat it doesn't send, the message jsut doesn't appear this is a good way to stop accidently leaking your coordinates if you aren't careful

**Comment by very-cashmoney** [comment]
why would you type your coords in chat feels dank man

**Comment by moaihax** [comment]
Seems like a brain issue if you need this

**Comment by TransRights** [comment]
Added in 0.10
