### ISSUE TITLE
Sorround hotbar BUG (if you need a video of bug dm me on discord DachaBager#8699)

### ISSUE THREAD

**Issue by DachaBager** [DarkiBoi/konas-issues#63]
There's a bug where when you eneable sorround you can't change item in you hotbar until you disable sorround here are my settings:
![image](https://user-images.githubusercontent.com/72751613/97755165-f9cb6480-1af8-11eb-9acd-f5071369073a.png)

**Comment by zyktex** [comment]
This has been fixed in 0.5.1
