### ISSUE TITLE
Bug, not being able to pick up water without LiquidInteract.

### ISSUE THREAD

**Issue by Hayliox** [DarkiBoi/konas-issues#79]
I have these modules turned on: 

LiquidInteract (kind of no choice rn)
EntityControl
Nametags
Fullbright
NoSlow
Tracers
Time
HUD
ESP

It won't let me pickup water with a bucket unless I activate LiquidInteract. I can place blocks, break them and even place water but can't pick it back up. I have no other clients, I even removed optifine and baritone but nothing changed.

**Comment by Ihackedsctrach** [comment]
thats really weird

**Comment by DarkiBoi** [comment]
thats weird, well look into it

**Comment by very-cashmoney** [comment]
any other clients brother

**Comment by Hayliox** [comment]
> 
> 
> any other clients brother

No, said it in the description. I don't even have optifine on. When I removed konas (which leaves me to the latest 1.12.2 forge) it works again. I can pickup water with any other clients or versions. When I play with Konas, it's the only client I have on.

**Comment by Ihackedsctrach** [comment]
then that would be something with konas instead of something with ur clients

**Comment by Hayliox** [comment]
> then that would be something with konas instead of something with ur clients

Yup that's why I'm here

**Comment by Ihackedsctrach** [comment]
then try using another client with liquif interact and see if that helps

**Comment by zyktex** [comment]
Fixed in 0.6
