### ISSUE TITLE
Continuation/Updated nametags suggestion

### ISSUE THREAD

**Issue by NotJohnmcswag** [DarkiBoi/konas-issues#80]
Remove the bar below armor and add an option whether to show numbers, bar or both and where to show them (below armor or above) 
Remove the | in between ping name and health (Or add an option to show it) 
Add an option on whether to show absorption health as gold or green
Add an outline option
Make the enchant text bigger and have an option to put it on the armor instead of above it
Add totempops option 
Add simple enchants option (if armor is maxed show "Maxed" instead of showing enchants)
Make the font bigger and add a customfont option
Add a command so you can change the font to whatever you like
Make the numbers on items instead of below them
Fix FPS drops when a lot of people are in visual range

**Comment by zyktex** [comment]
Some of these have already been addressed. The FPS drops are inevitable; however, once we add an option to disable item rendering turning off armor rendering might improve performance.
