### ISSUE TITLE
client idea

### ISSUE THREAD

**Issue by Tux8068** [DarkiBoi/konas-issues#88]
allow the opening of the gui in the main menu/homescreen,  this will allow users to disable modules that kick them repeatedly without having to join a single game this will save users loads of time in my opinion

**Comment by zyktex** [comment]
Modules such as PacketFly already automatically disable when joining a world. Implementing a custom GUI would require a lot of effort, and would be more hacky than just joining a sp world and disabling that module. Most servers have a relog cooldown anyways so no time would be lost.
