### ISSUE TITLE
Bunch of suggestions for modules and fixes (by

### ISSUE THREAD

**Issue by wallacearney** [DarkiBoi/konas-issues#96]
1. the sync thing for colors would be cool to see. I explained about that in the discord 
2. Bed aura seems to prefer placing on ground rather then air in 1.13 servers could just be me but it happens often.
3. add offhand swing to ca, A lot of people prefer it 
4. more compatibility with other clients right now especially xulu phobos and wp2.
5. bypassing step on 2bpvp and other servers would be nice as right now the one here lags back on most servers could just be me aswell.
6. for ca add disable when surround
7. on nametags add an option to not show the other players armor/ enchantments on the nametag.
8.for colors add something where you can change the saturation value and wether if the rainbow is rolling. 
9. bpyassing onground speed for more servers including 2bpvp would be cool aswell

thank you these are just some suggestions, most being personal preference but to see these in a future update would be cool tahnk you
-flat

**Comment by cheroso1337** [comment]
(by

**Comment by zyktex** [comment]
Could you please explain what you mean by 1 here? Also for 3 that will make no difference and on some servers it might prevent you from consuming mainhand items while offhanding. Lastly, the current step should work fine up to 2.5 blocks on 2b2t (and 2bpvp). Anything higher than that is essentially impossible, as even if you bypass packet limitations, you will get setback.

**Comment by waspgod** [comment]
> Could you please explain what you mean by 1 here? Also for 3 that will make no difference and on some servers it might prevent you from consuming mainhand items while offhanding. Lastly, the current step should work fine up to 2.5 blocks on 2b2t (and 2bpvp). Anything higher than that is essentially impossible, as even if you bypass packet limitations, you will get setback.

this was made when 0.5.2 was out
