### ISSUE TITLE
GraalVM/Nashorn Scripting

### ISSUE THREAD

**Issue by Vonr** [DarkiBoi/konas-issues#97]
Idea shamelessly stolen from liquidbounce's nashorn scripting system.
If cookiedragon was here he would probably tell me it lessens obfuscation and is a bad idea so it's probably a bad idea.

basically write scripts for modules/commands in js, load on mc launch, execute js stuff with graal/nashorn

GraalVM better for performance but Nashorn means you can skid LB

**Comment by zyktex** [comment]
We will not offer 3rd party addon support in the near future
