### ISSUE TITLE
Freecam issue

### ISSUE THREAD

**Issue by KAI66684** [DarkiBoi/konas-issues#98]
![2020-11-09_19 52 07](https://user-images.githubusercontent.com/65884390/98591486-39980600-22c8-11eb-8c7b-df178de5c7f7.png)
freecam showing hole esp

**Comment by zyktex** [comment]
This is not a konas issue. The other client's HoleESP does not properly transform the camera. It uses the player instead of the render position. Please contact the other client's developer, as this is their bug.
